/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_dolit_DLBT_IOWrapper */

#ifndef _Included_cn_dolit_DLBT_IOWrapper
#define _Included_cn_dolit_DLBT_IOWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_dolit_DLBT_IOWrapper
 * Method:    Rename
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Lcn/dolit/DLBT/IOResult;
 */
JNIEXPORT jobject JNICALL Java_cn_dolit_DLBT_IOWrapper_Rename
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     cn_dolit_DLBT_IOWrapper
 * Method:    Remove
 * Signature: (Ljava/lang/String;)Lcn/dolit/DLBT/IOResult;
 */
JNIEXPORT jobject JNICALL Java_cn_dolit_DLBT_IOWrapper_Remove
  (JNIEnv *, jobject, jstring);

/*
 * Class:     cn_dolit_DLBT_IOWrapper
 * Method:    ListDir
 * Signature: (Ljava/lang/String;)Lcn/dolit/DLBT/IOResult;
 */
JNIEXPORT jobject JNICALL Java_cn_dolit_DLBT_IOWrapper_ListDir
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
